context:
  name: csp-gateway
  version: "2.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
    url: https://pypi.org/packages/source/c/csp-gateway/csp_gateway-${{ version }}.tar.gz
    sha256: 8577243f11798cf23bb304e8fc13ae9d6d2a86aa617e3fe05a2e63fa32a62f43

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points: 
      - cspgateway-start = csp_gateway.server.cli:main
      - cspgateway_start = csp_gateway.server.cli:main
      - csp-gateway-start = csp_gateway.server.cli:main
      - csp_gateway_start = csp_gateway.server.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-jupyter-builder
    - pnpm
  run:
    - python >=${{ python_min }}
    - aiohttp
    - aiostream
    - atomic-counter >=0.1.3
    - ccflow >=0.3.0,<0.5.0
    - colorlog
    - csp >=0.8.0,<1
    - deprecation
    - duckdb >=0.10
    - fastapi >=0.110
    - fsspec
    - httpx
    - hydra-core
    - janus
    - jsonref
    - nest-asyncio
    - omegaconf
    - orjson
    - packaging
    - perspective >=3.3,!=3.4.0,<4
    - psutil
    - pyarrow
    - pydantic >=2
    - uvicorn >=0.28.1,<0.31
    - uvloop
    - websockets

tests:
  - python:
      imports:
        - csp_gateway
        - csp_gateway.server
        - csp_gateway.client
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
    - csp-gateway-start --help

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Application framework built on CSP
  homepage: https://github.com/point72/csp-gateway
  repository: https://github.com/point72/csp-gateway

extra:
  recipe-maintainers:
    - arhamchopra
    - hintse
    - neejweej
    - ptomecek
    - timkpaine
